# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "/Applications/CMake 2.8-6.app/Contents/bin/cmake"

# The command to remove a file.
RM = "/Applications/CMake 2.8-6.app/Contents/bin/cmake" -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = "/Applications/CMake 2.8-6.app/Contents/bin/ccmake"

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/maurizio/work/t11/git/osg

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/maurizio/work/t11/git/osg

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"/Applications/CMake 2.8-6.app/Contents/bin/ccmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	"/Applications/CMake 2.8-6.app/Contents/bin/cmake" -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	"/Applications/CMake 2.8-6.app/Contents/bin/cmake" -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	"/Applications/CMake 2.8-6.app/Contents/bin/cmake" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	"/Applications/CMake 2.8-6.app/Contents/bin/cmake" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"libopenscenegraph\" \"libopenscenegraph-dev\" \"libopenthreads\" \"libopenthreads-dev\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"/Applications/CMake 2.8-6.app/Contents/bin/cmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/maurizio/work/t11/git/osg/CMakeFiles /Users/maurizio/work/t11/git/osg/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/maurizio/work/t11/git/osg/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named OpenThreads

# Build rule for target.
OpenThreads: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 OpenThreads
.PHONY : OpenThreads

# fast build rule for target.
OpenThreads/fast:
	$(MAKE) -f src/OpenThreads/pthreads/CMakeFiles/OpenThreads.dir/build.make src/OpenThreads/pthreads/CMakeFiles/OpenThreads.dir/build
.PHONY : OpenThreads/fast

#=============================================================================
# Target rules for targets named osg

# Build rule for target.
osg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osg
.PHONY : osg

# fast build rule for target.
osg/fast:
	$(MAKE) -f src/osg/CMakeFiles/osg.dir/build.make src/osg/CMakeFiles/osg.dir/build
.PHONY : osg/fast

#=============================================================================
# Target rules for targets named osgDB

# Build rule for target.
osgDB: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgDB
.PHONY : osgDB

# fast build rule for target.
osgDB/fast:
	$(MAKE) -f src/osgDB/CMakeFiles/osgDB.dir/build.make src/osgDB/CMakeFiles/osgDB.dir/build
.PHONY : osgDB/fast

#=============================================================================
# Target rules for targets named osgUtil

# Build rule for target.
osgUtil: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgUtil
.PHONY : osgUtil

# fast build rule for target.
osgUtil/fast:
	$(MAKE) -f src/osgUtil/CMakeFiles/osgUtil.dir/build.make src/osgUtil/CMakeFiles/osgUtil.dir/build
.PHONY : osgUtil/fast

#=============================================================================
# Target rules for targets named osgGA

# Build rule for target.
osgGA: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgGA
.PHONY : osgGA

# fast build rule for target.
osgGA/fast:
	$(MAKE) -f src/osgGA/CMakeFiles/osgGA.dir/build.make src/osgGA/CMakeFiles/osgGA.dir/build
.PHONY : osgGA/fast

#=============================================================================
# Target rules for targets named osgText

# Build rule for target.
osgText: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgText
.PHONY : osgText

# fast build rule for target.
osgText/fast:
	$(MAKE) -f src/osgText/CMakeFiles/osgText.dir/build.make src/osgText/CMakeFiles/osgText.dir/build
.PHONY : osgText/fast

#=============================================================================
# Target rules for targets named osgViewer

# Build rule for target.
osgViewer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgViewer
.PHONY : osgViewer

# fast build rule for target.
osgViewer/fast:
	$(MAKE) -f src/osgViewer/CMakeFiles/osgViewer.dir/build.make src/osgViewer/CMakeFiles/osgViewer.dir/build
.PHONY : osgViewer/fast

#=============================================================================
# Target rules for targets named osgAnimation

# Build rule for target.
osgAnimation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgAnimation
.PHONY : osgAnimation

# fast build rule for target.
osgAnimation/fast:
	$(MAKE) -f src/osgAnimation/CMakeFiles/osgAnimation.dir/build.make src/osgAnimation/CMakeFiles/osgAnimation.dir/build
.PHONY : osgAnimation/fast

#=============================================================================
# Target rules for targets named osgFX

# Build rule for target.
osgFX: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgFX
.PHONY : osgFX

# fast build rule for target.
osgFX/fast:
	$(MAKE) -f src/osgFX/CMakeFiles/osgFX.dir/build.make src/osgFX/CMakeFiles/osgFX.dir/build
.PHONY : osgFX/fast

#=============================================================================
# Target rules for targets named osgManipulator

# Build rule for target.
osgManipulator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgManipulator
.PHONY : osgManipulator

# fast build rule for target.
osgManipulator/fast:
	$(MAKE) -f src/osgManipulator/CMakeFiles/osgManipulator.dir/build.make src/osgManipulator/CMakeFiles/osgManipulator.dir/build
.PHONY : osgManipulator/fast

#=============================================================================
# Target rules for targets named osgParticle

# Build rule for target.
osgParticle: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgParticle
.PHONY : osgParticle

# fast build rule for target.
osgParticle/fast:
	$(MAKE) -f src/osgParticle/CMakeFiles/osgParticle.dir/build.make src/osgParticle/CMakeFiles/osgParticle.dir/build
.PHONY : osgParticle/fast

#=============================================================================
# Target rules for targets named osgPresentation

# Build rule for target.
osgPresentation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgPresentation
.PHONY : osgPresentation

# fast build rule for target.
osgPresentation/fast:
	$(MAKE) -f src/osgPresentation/CMakeFiles/osgPresentation.dir/build.make src/osgPresentation/CMakeFiles/osgPresentation.dir/build
.PHONY : osgPresentation/fast

#=============================================================================
# Target rules for targets named osgShadow

# Build rule for target.
osgShadow: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgShadow
.PHONY : osgShadow

# fast build rule for target.
osgShadow/fast:
	$(MAKE) -f src/osgShadow/CMakeFiles/osgShadow.dir/build.make src/osgShadow/CMakeFiles/osgShadow.dir/build
.PHONY : osgShadow/fast

#=============================================================================
# Target rules for targets named osgSim

# Build rule for target.
osgSim: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgSim
.PHONY : osgSim

# fast build rule for target.
osgSim/fast:
	$(MAKE) -f src/osgSim/CMakeFiles/osgSim.dir/build.make src/osgSim/CMakeFiles/osgSim.dir/build
.PHONY : osgSim/fast

#=============================================================================
# Target rules for targets named osgTerrain

# Build rule for target.
osgTerrain: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgTerrain
.PHONY : osgTerrain

# fast build rule for target.
osgTerrain/fast:
	$(MAKE) -f src/osgTerrain/CMakeFiles/osgTerrain.dir/build.make src/osgTerrain/CMakeFiles/osgTerrain.dir/build
.PHONY : osgTerrain/fast

#=============================================================================
# Target rules for targets named osgWidget

# Build rule for target.
osgWidget: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgWidget
.PHONY : osgWidget

# fast build rule for target.
osgWidget/fast:
	$(MAKE) -f src/osgWidget/CMakeFiles/osgWidget.dir/build.make src/osgWidget/CMakeFiles/osgWidget.dir/build
.PHONY : osgWidget/fast

#=============================================================================
# Target rules for targets named osgVolume

# Build rule for target.
osgVolume: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgVolume
.PHONY : osgVolume

# fast build rule for target.
osgVolume/fast:
	$(MAKE) -f src/osgVolume/CMakeFiles/osgVolume.dir/build.make src/osgVolume/CMakeFiles/osgVolume.dir/build
.PHONY : osgVolume/fast

#=============================================================================
# Target rules for targets named osgdb_serializers_osg

# Build rule for target.
osgdb_serializers_osg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_serializers_osg
.PHONY : osgdb_serializers_osg

# fast build rule for target.
osgdb_serializers_osg/fast:
	$(MAKE) -f src/osgWrappers/serializers/osg/CMakeFiles/osgdb_serializers_osg.dir/build.make src/osgWrappers/serializers/osg/CMakeFiles/osgdb_serializers_osg.dir/build
.PHONY : osgdb_serializers_osg/fast

#=============================================================================
# Target rules for targets named osgdb_serializers_osganimation

# Build rule for target.
osgdb_serializers_osganimation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_serializers_osganimation
.PHONY : osgdb_serializers_osganimation

# fast build rule for target.
osgdb_serializers_osganimation/fast:
	$(MAKE) -f src/osgWrappers/serializers/osgAnimation/CMakeFiles/osgdb_serializers_osganimation.dir/build.make src/osgWrappers/serializers/osgAnimation/CMakeFiles/osgdb_serializers_osganimation.dir/build
.PHONY : osgdb_serializers_osganimation/fast

#=============================================================================
# Target rules for targets named osgdb_serializers_osgfx

# Build rule for target.
osgdb_serializers_osgfx: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_serializers_osgfx
.PHONY : osgdb_serializers_osgfx

# fast build rule for target.
osgdb_serializers_osgfx/fast:
	$(MAKE) -f src/osgWrappers/serializers/osgFX/CMakeFiles/osgdb_serializers_osgfx.dir/build.make src/osgWrappers/serializers/osgFX/CMakeFiles/osgdb_serializers_osgfx.dir/build
.PHONY : osgdb_serializers_osgfx/fast

#=============================================================================
# Target rules for targets named osgdb_serializers_osgmanipulator

# Build rule for target.
osgdb_serializers_osgmanipulator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_serializers_osgmanipulator
.PHONY : osgdb_serializers_osgmanipulator

# fast build rule for target.
osgdb_serializers_osgmanipulator/fast:
	$(MAKE) -f src/osgWrappers/serializers/osgManipulator/CMakeFiles/osgdb_serializers_osgmanipulator.dir/build.make src/osgWrappers/serializers/osgManipulator/CMakeFiles/osgdb_serializers_osgmanipulator.dir/build
.PHONY : osgdb_serializers_osgmanipulator/fast

#=============================================================================
# Target rules for targets named osgdb_serializers_osgparticle

# Build rule for target.
osgdb_serializers_osgparticle: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_serializers_osgparticle
.PHONY : osgdb_serializers_osgparticle

# fast build rule for target.
osgdb_serializers_osgparticle/fast:
	$(MAKE) -f src/osgWrappers/serializers/osgParticle/CMakeFiles/osgdb_serializers_osgparticle.dir/build.make src/osgWrappers/serializers/osgParticle/CMakeFiles/osgdb_serializers_osgparticle.dir/build
.PHONY : osgdb_serializers_osgparticle/fast

#=============================================================================
# Target rules for targets named osgdb_serializers_osgsim

# Build rule for target.
osgdb_serializers_osgsim: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_serializers_osgsim
.PHONY : osgdb_serializers_osgsim

# fast build rule for target.
osgdb_serializers_osgsim/fast:
	$(MAKE) -f src/osgWrappers/serializers/osgSim/CMakeFiles/osgdb_serializers_osgsim.dir/build.make src/osgWrappers/serializers/osgSim/CMakeFiles/osgdb_serializers_osgsim.dir/build
.PHONY : osgdb_serializers_osgsim/fast

#=============================================================================
# Target rules for targets named osgdb_serializers_osgshadow

# Build rule for target.
osgdb_serializers_osgshadow: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_serializers_osgshadow
.PHONY : osgdb_serializers_osgshadow

# fast build rule for target.
osgdb_serializers_osgshadow/fast:
	$(MAKE) -f src/osgWrappers/serializers/osgShadow/CMakeFiles/osgdb_serializers_osgshadow.dir/build.make src/osgWrappers/serializers/osgShadow/CMakeFiles/osgdb_serializers_osgshadow.dir/build
.PHONY : osgdb_serializers_osgshadow/fast

#=============================================================================
# Target rules for targets named osgdb_serializers_osgterrain

# Build rule for target.
osgdb_serializers_osgterrain: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_serializers_osgterrain
.PHONY : osgdb_serializers_osgterrain

# fast build rule for target.
osgdb_serializers_osgterrain/fast:
	$(MAKE) -f src/osgWrappers/serializers/osgTerrain/CMakeFiles/osgdb_serializers_osgterrain.dir/build.make src/osgWrappers/serializers/osgTerrain/CMakeFiles/osgdb_serializers_osgterrain.dir/build
.PHONY : osgdb_serializers_osgterrain/fast

#=============================================================================
# Target rules for targets named osgdb_serializers_osgtext

# Build rule for target.
osgdb_serializers_osgtext: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_serializers_osgtext
.PHONY : osgdb_serializers_osgtext

# fast build rule for target.
osgdb_serializers_osgtext/fast:
	$(MAKE) -f src/osgWrappers/serializers/osgText/CMakeFiles/osgdb_serializers_osgtext.dir/build.make src/osgWrappers/serializers/osgText/CMakeFiles/osgdb_serializers_osgtext.dir/build
.PHONY : osgdb_serializers_osgtext/fast

#=============================================================================
# Target rules for targets named osgdb_serializers_osgvolume

# Build rule for target.
osgdb_serializers_osgvolume: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_serializers_osgvolume
.PHONY : osgdb_serializers_osgvolume

# fast build rule for target.
osgdb_serializers_osgvolume/fast:
	$(MAKE) -f src/osgWrappers/serializers/osgVolume/CMakeFiles/osgdb_serializers_osgvolume.dir/build.make src/osgWrappers/serializers/osgVolume/CMakeFiles/osgdb_serializers_osgvolume.dir/build
.PHONY : osgdb_serializers_osgvolume/fast

#=============================================================================
# Target rules for targets named osgdb_deprecated_osg

# Build rule for target.
osgdb_deprecated_osg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_deprecated_osg
.PHONY : osgdb_deprecated_osg

# fast build rule for target.
osgdb_deprecated_osg/fast:
	$(MAKE) -f src/osgWrappers/deprecated-dotosg/osg/CMakeFiles/osgdb_deprecated_osg.dir/build.make src/osgWrappers/deprecated-dotosg/osg/CMakeFiles/osgdb_deprecated_osg.dir/build
.PHONY : osgdb_deprecated_osg/fast

#=============================================================================
# Target rules for targets named osgdb_deprecated_osgparticle

# Build rule for target.
osgdb_deprecated_osgparticle: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_deprecated_osgparticle
.PHONY : osgdb_deprecated_osgparticle

# fast build rule for target.
osgdb_deprecated_osgparticle/fast:
	$(MAKE) -f src/osgWrappers/deprecated-dotosg/osgParticle/CMakeFiles/osgdb_deprecated_osgparticle.dir/build.make src/osgWrappers/deprecated-dotosg/osgParticle/CMakeFiles/osgdb_deprecated_osgparticle.dir/build
.PHONY : osgdb_deprecated_osgparticle/fast

#=============================================================================
# Target rules for targets named osgdb_deprecated_osganimation

# Build rule for target.
osgdb_deprecated_osganimation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_deprecated_osganimation
.PHONY : osgdb_deprecated_osganimation

# fast build rule for target.
osgdb_deprecated_osganimation/fast:
	$(MAKE) -f src/osgWrappers/deprecated-dotosg/osgAnimation/CMakeFiles/osgdb_deprecated_osganimation.dir/build.make src/osgWrappers/deprecated-dotosg/osgAnimation/CMakeFiles/osgdb_deprecated_osganimation.dir/build
.PHONY : osgdb_deprecated_osganimation/fast

#=============================================================================
# Target rules for targets named osgdb_deprecated_osgfx

# Build rule for target.
osgdb_deprecated_osgfx: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_deprecated_osgfx
.PHONY : osgdb_deprecated_osgfx

# fast build rule for target.
osgdb_deprecated_osgfx/fast:
	$(MAKE) -f src/osgWrappers/deprecated-dotosg/osgFX/CMakeFiles/osgdb_deprecated_osgfx.dir/build.make src/osgWrappers/deprecated-dotosg/osgFX/CMakeFiles/osgdb_deprecated_osgfx.dir/build
.PHONY : osgdb_deprecated_osgfx/fast

#=============================================================================
# Target rules for targets named osgdb_deprecated_osgsim

# Build rule for target.
osgdb_deprecated_osgsim: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_deprecated_osgsim
.PHONY : osgdb_deprecated_osgsim

# fast build rule for target.
osgdb_deprecated_osgsim/fast:
	$(MAKE) -f src/osgWrappers/deprecated-dotosg/osgSim/CMakeFiles/osgdb_deprecated_osgsim.dir/build.make src/osgWrappers/deprecated-dotosg/osgSim/CMakeFiles/osgdb_deprecated_osgsim.dir/build
.PHONY : osgdb_deprecated_osgsim/fast

#=============================================================================
# Target rules for targets named osgdb_deprecated_osgtext

# Build rule for target.
osgdb_deprecated_osgtext: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_deprecated_osgtext
.PHONY : osgdb_deprecated_osgtext

# fast build rule for target.
osgdb_deprecated_osgtext/fast:
	$(MAKE) -f src/osgWrappers/deprecated-dotosg/osgText/CMakeFiles/osgdb_deprecated_osgtext.dir/build.make src/osgWrappers/deprecated-dotosg/osgText/CMakeFiles/osgdb_deprecated_osgtext.dir/build
.PHONY : osgdb_deprecated_osgtext/fast

#=============================================================================
# Target rules for targets named osgdb_deprecated_osgviewer

# Build rule for target.
osgdb_deprecated_osgviewer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_deprecated_osgviewer
.PHONY : osgdb_deprecated_osgviewer

# fast build rule for target.
osgdb_deprecated_osgviewer/fast:
	$(MAKE) -f src/osgWrappers/deprecated-dotosg/osgViewer/CMakeFiles/osgdb_deprecated_osgviewer.dir/build.make src/osgWrappers/deprecated-dotosg/osgViewer/CMakeFiles/osgdb_deprecated_osgviewer.dir/build
.PHONY : osgdb_deprecated_osgviewer/fast

#=============================================================================
# Target rules for targets named osgdb_deprecated_osgshadow

# Build rule for target.
osgdb_deprecated_osgshadow: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_deprecated_osgshadow
.PHONY : osgdb_deprecated_osgshadow

# fast build rule for target.
osgdb_deprecated_osgshadow/fast:
	$(MAKE) -f src/osgWrappers/deprecated-dotosg/osgShadow/CMakeFiles/osgdb_deprecated_osgshadow.dir/build.make src/osgWrappers/deprecated-dotosg/osgShadow/CMakeFiles/osgdb_deprecated_osgshadow.dir/build
.PHONY : osgdb_deprecated_osgshadow/fast

#=============================================================================
# Target rules for targets named osgdb_deprecated_osgterrain

# Build rule for target.
osgdb_deprecated_osgterrain: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_deprecated_osgterrain
.PHONY : osgdb_deprecated_osgterrain

# fast build rule for target.
osgdb_deprecated_osgterrain/fast:
	$(MAKE) -f src/osgWrappers/deprecated-dotosg/osgTerrain/CMakeFiles/osgdb_deprecated_osgterrain.dir/build.make src/osgWrappers/deprecated-dotosg/osgTerrain/CMakeFiles/osgdb_deprecated_osgterrain.dir/build
.PHONY : osgdb_deprecated_osgterrain/fast

#=============================================================================
# Target rules for targets named osgdb_deprecated_osgvolume

# Build rule for target.
osgdb_deprecated_osgvolume: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_deprecated_osgvolume
.PHONY : osgdb_deprecated_osgvolume

# fast build rule for target.
osgdb_deprecated_osgvolume/fast:
	$(MAKE) -f src/osgWrappers/deprecated-dotosg/osgVolume/CMakeFiles/osgdb_deprecated_osgvolume.dir/build.make src/osgWrappers/deprecated-dotosg/osgVolume/CMakeFiles/osgdb_deprecated_osgvolume.dir/build
.PHONY : osgdb_deprecated_osgvolume/fast

#=============================================================================
# Target rules for targets named osgdb_deprecated_osgwidget

# Build rule for target.
osgdb_deprecated_osgwidget: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_deprecated_osgwidget
.PHONY : osgdb_deprecated_osgwidget

# fast build rule for target.
osgdb_deprecated_osgwidget/fast:
	$(MAKE) -f src/osgWrappers/deprecated-dotosg/osgWidget/CMakeFiles/osgdb_deprecated_osgwidget.dir/build.make src/osgWrappers/deprecated-dotosg/osgWidget/CMakeFiles/osgdb_deprecated_osgwidget.dir/build
.PHONY : osgdb_deprecated_osgwidget/fast

#=============================================================================
# Target rules for targets named osgdb_osga

# Build rule for target.
osgdb_osga: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_osga
.PHONY : osgdb_osga

# fast build rule for target.
osgdb_osga/fast:
	$(MAKE) -f src/osgPlugins/osga/CMakeFiles/osgdb_osga.dir/build.make src/osgPlugins/osga/CMakeFiles/osgdb_osga.dir/build
.PHONY : osgdb_osga/fast

#=============================================================================
# Target rules for targets named osgdb_rot

# Build rule for target.
osgdb_rot: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_rot
.PHONY : osgdb_rot

# fast build rule for target.
osgdb_rot/fast:
	$(MAKE) -f src/osgPlugins/rot/CMakeFiles/osgdb_rot.dir/build.make src/osgPlugins/rot/CMakeFiles/osgdb_rot.dir/build
.PHONY : osgdb_rot/fast

#=============================================================================
# Target rules for targets named osgdb_scale

# Build rule for target.
osgdb_scale: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_scale
.PHONY : osgdb_scale

# fast build rule for target.
osgdb_scale/fast:
	$(MAKE) -f src/osgPlugins/scale/CMakeFiles/osgdb_scale.dir/build.make src/osgPlugins/scale/CMakeFiles/osgdb_scale.dir/build
.PHONY : osgdb_scale/fast

#=============================================================================
# Target rules for targets named osgdb_trans

# Build rule for target.
osgdb_trans: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_trans
.PHONY : osgdb_trans

# fast build rule for target.
osgdb_trans/fast:
	$(MAKE) -f src/osgPlugins/trans/CMakeFiles/osgdb_trans.dir/build.make src/osgPlugins/trans/CMakeFiles/osgdb_trans.dir/build
.PHONY : osgdb_trans/fast

#=============================================================================
# Target rules for targets named osgdb_normals

# Build rule for target.
osgdb_normals: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_normals
.PHONY : osgdb_normals

# fast build rule for target.
osgdb_normals/fast:
	$(MAKE) -f src/osgPlugins/normals/CMakeFiles/osgdb_normals.dir/build.make src/osgPlugins/normals/CMakeFiles/osgdb_normals.dir/build
.PHONY : osgdb_normals/fast

#=============================================================================
# Target rules for targets named osgdb_revisions

# Build rule for target.
osgdb_revisions: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_revisions
.PHONY : osgdb_revisions

# fast build rule for target.
osgdb_revisions/fast:
	$(MAKE) -f src/osgPlugins/revisions/CMakeFiles/osgdb_revisions.dir/build.make src/osgPlugins/revisions/CMakeFiles/osgdb_revisions.dir/build
.PHONY : osgdb_revisions/fast

#=============================================================================
# Target rules for targets named osgdb_osgviewer

# Build rule for target.
osgdb_osgviewer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_osgviewer
.PHONY : osgdb_osgviewer

# fast build rule for target.
osgdb_osgviewer/fast:
	$(MAKE) -f src/osgPlugins/view/CMakeFiles/osgdb_osgviewer.dir/build.make src/osgPlugins/view/CMakeFiles/osgdb_osgviewer.dir/build
.PHONY : osgdb_osgviewer/fast

#=============================================================================
# Target rules for targets named osgdb_osgshadow

# Build rule for target.
osgdb_osgshadow: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_osgshadow
.PHONY : osgdb_osgshadow

# fast build rule for target.
osgdb_osgshadow/fast:
	$(MAKE) -f src/osgPlugins/shadow/CMakeFiles/osgdb_osgshadow.dir/build.make src/osgPlugins/shadow/CMakeFiles/osgdb_osgshadow.dir/build
.PHONY : osgdb_osgshadow/fast

#=============================================================================
# Target rules for targets named osgdb_osgterrain

# Build rule for target.
osgdb_osgterrain: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_osgterrain
.PHONY : osgdb_osgterrain

# fast build rule for target.
osgdb_osgterrain/fast:
	$(MAKE) -f src/osgPlugins/terrain/CMakeFiles/osgdb_osgterrain.dir/build.make src/osgPlugins/terrain/CMakeFiles/osgdb_osgterrain.dir/build
.PHONY : osgdb_osgterrain/fast

#=============================================================================
# Target rules for targets named osgdb_osg

# Build rule for target.
osgdb_osg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_osg
.PHONY : osgdb_osg

# fast build rule for target.
osgdb_osg/fast:
	$(MAKE) -f src/osgPlugins/osg/CMakeFiles/osgdb_osg.dir/build.make src/osgPlugins/osg/CMakeFiles/osgdb_osg.dir/build
.PHONY : osgdb_osg/fast

#=============================================================================
# Target rules for targets named osgdb_ive

# Build rule for target.
osgdb_ive: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_ive
.PHONY : osgdb_ive

# fast build rule for target.
osgdb_ive/fast:
	$(MAKE) -f src/osgPlugins/ive/CMakeFiles/osgdb_ive.dir/build.make src/osgPlugins/ive/CMakeFiles/osgdb_ive.dir/build
.PHONY : osgdb_ive/fast

#=============================================================================
# Target rules for targets named osgdb_cfg

# Build rule for target.
osgdb_cfg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_cfg
.PHONY : osgdb_cfg

# fast build rule for target.
osgdb_cfg/fast:
	$(MAKE) -f src/osgPlugins/cfg/CMakeFiles/osgdb_cfg.dir/build.make src/osgPlugins/cfg/CMakeFiles/osgdb_cfg.dir/build
.PHONY : osgdb_cfg/fast

#=============================================================================
# Target rules for targets named osgdb_glsl

# Build rule for target.
osgdb_glsl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_glsl
.PHONY : osgdb_glsl

# fast build rule for target.
osgdb_glsl/fast:
	$(MAKE) -f src/osgPlugins/glsl/CMakeFiles/osgdb_glsl.dir/build.make src/osgPlugins/glsl/CMakeFiles/osgdb_glsl.dir/build
.PHONY : osgdb_glsl/fast

#=============================================================================
# Target rules for targets named osgdb_rgb

# Build rule for target.
osgdb_rgb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_rgb
.PHONY : osgdb_rgb

# fast build rule for target.
osgdb_rgb/fast:
	$(MAKE) -f src/osgPlugins/rgb/CMakeFiles/osgdb_rgb.dir/build.make src/osgPlugins/rgb/CMakeFiles/osgdb_rgb.dir/build
.PHONY : osgdb_rgb/fast

#=============================================================================
# Target rules for targets named osgdb_bmp

# Build rule for target.
osgdb_bmp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_bmp
.PHONY : osgdb_bmp

# fast build rule for target.
osgdb_bmp/fast:
	$(MAKE) -f src/osgPlugins/bmp/CMakeFiles/osgdb_bmp.dir/build.make src/osgPlugins/bmp/CMakeFiles/osgdb_bmp.dir/build
.PHONY : osgdb_bmp/fast

#=============================================================================
# Target rules for targets named osgdb_pnm

# Build rule for target.
osgdb_pnm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_pnm
.PHONY : osgdb_pnm

# fast build rule for target.
osgdb_pnm/fast:
	$(MAKE) -f src/osgPlugins/pnm/CMakeFiles/osgdb_pnm.dir/build.make src/osgPlugins/pnm/CMakeFiles/osgdb_pnm.dir/build
.PHONY : osgdb_pnm/fast

#=============================================================================
# Target rules for targets named osgdb_dds

# Build rule for target.
osgdb_dds: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_dds
.PHONY : osgdb_dds

# fast build rule for target.
osgdb_dds/fast:
	$(MAKE) -f src/osgPlugins/dds/CMakeFiles/osgdb_dds.dir/build.make src/osgPlugins/dds/CMakeFiles/osgdb_dds.dir/build
.PHONY : osgdb_dds/fast

#=============================================================================
# Target rules for targets named osgdb_tga

# Build rule for target.
osgdb_tga: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_tga
.PHONY : osgdb_tga

# fast build rule for target.
osgdb_tga/fast:
	$(MAKE) -f src/osgPlugins/tga/CMakeFiles/osgdb_tga.dir/build.make src/osgPlugins/tga/CMakeFiles/osgdb_tga.dir/build
.PHONY : osgdb_tga/fast

#=============================================================================
# Target rules for targets named osgdb_hdr

# Build rule for target.
osgdb_hdr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_hdr
.PHONY : osgdb_hdr

# fast build rule for target.
osgdb_hdr/fast:
	$(MAKE) -f src/osgPlugins/hdr/CMakeFiles/osgdb_hdr.dir/build.make src/osgPlugins/hdr/CMakeFiles/osgdb_hdr.dir/build
.PHONY : osgdb_hdr/fast

#=============================================================================
# Target rules for targets named osgdb_dot

# Build rule for target.
osgdb_dot: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_dot
.PHONY : osgdb_dot

# fast build rule for target.
osgdb_dot/fast:
	$(MAKE) -f src/osgPlugins/dot/CMakeFiles/osgdb_dot.dir/build.make src/osgPlugins/dot/CMakeFiles/osgdb_dot.dir/build
.PHONY : osgdb_dot/fast

#=============================================================================
# Target rules for targets named osgdb_vtf

# Build rule for target.
osgdb_vtf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_vtf
.PHONY : osgdb_vtf

# fast build rule for target.
osgdb_vtf/fast:
	$(MAKE) -f src/osgPlugins/vtf/CMakeFiles/osgdb_vtf.dir/build.make src/osgPlugins/vtf/CMakeFiles/osgdb_vtf.dir/build
.PHONY : osgdb_vtf/fast

#=============================================================================
# Target rules for targets named osgdb_3dc

# Build rule for target.
osgdb_3dc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_3dc
.PHONY : osgdb_3dc

# fast build rule for target.
osgdb_3dc/fast:
	$(MAKE) -f src/osgPlugins/3dc/CMakeFiles/osgdb_3dc.dir/build.make src/osgPlugins/3dc/CMakeFiles/osgdb_3dc.dir/build
.PHONY : osgdb_3dc/fast

#=============================================================================
# Target rules for targets named osgdb_p3d

# Build rule for target.
osgdb_p3d: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_p3d
.PHONY : osgdb_p3d

# fast build rule for target.
osgdb_p3d/fast:
	$(MAKE) -f src/osgPlugins/p3d/CMakeFiles/osgdb_p3d.dir/build.make src/osgPlugins/p3d/CMakeFiles/osgdb_p3d.dir/build
.PHONY : osgdb_p3d/fast

#=============================================================================
# Target rules for targets named osgdb_curl

# Build rule for target.
osgdb_curl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_curl
.PHONY : osgdb_curl

# fast build rule for target.
osgdb_curl/fast:
	$(MAKE) -f src/osgPlugins/curl/CMakeFiles/osgdb_curl.dir/build.make src/osgPlugins/curl/CMakeFiles/osgdb_curl.dir/build
.PHONY : osgdb_curl/fast

#=============================================================================
# Target rules for targets named osgdb_gz

# Build rule for target.
osgdb_gz: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_gz
.PHONY : osgdb_gz

# fast build rule for target.
osgdb_gz/fast:
	$(MAKE) -f src/osgPlugins/gz/CMakeFiles/osgdb_gz.dir/build.make src/osgPlugins/gz/CMakeFiles/osgdb_gz.dir/build
.PHONY : osgdb_gz/fast

#=============================================================================
# Target rules for targets named osgdb_lwo

# Build rule for target.
osgdb_lwo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_lwo
.PHONY : osgdb_lwo

# fast build rule for target.
osgdb_lwo/fast:
	$(MAKE) -f src/osgPlugins/lwo/CMakeFiles/osgdb_lwo.dir/build.make src/osgPlugins/lwo/CMakeFiles/osgdb_lwo.dir/build
.PHONY : osgdb_lwo/fast

#=============================================================================
# Target rules for targets named osgdb_dw

# Build rule for target.
osgdb_dw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_dw
.PHONY : osgdb_dw

# fast build rule for target.
osgdb_dw/fast:
	$(MAKE) -f src/osgPlugins/dw/CMakeFiles/osgdb_dw.dir/build.make src/osgPlugins/dw/CMakeFiles/osgdb_dw.dir/build
.PHONY : osgdb_dw/fast

#=============================================================================
# Target rules for targets named osgdb_bvh

# Build rule for target.
osgdb_bvh: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_bvh
.PHONY : osgdb_bvh

# fast build rule for target.
osgdb_bvh/fast:
	$(MAKE) -f src/osgPlugins/bvh/CMakeFiles/osgdb_bvh.dir/build.make src/osgPlugins/bvh/CMakeFiles/osgdb_bvh.dir/build
.PHONY : osgdb_bvh/fast

#=============================================================================
# Target rules for targets named osgdb_x

# Build rule for target.
osgdb_x: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_x
.PHONY : osgdb_x

# fast build rule for target.
osgdb_x/fast:
	$(MAKE) -f src/osgPlugins/x/CMakeFiles/osgdb_x.dir/build.make src/osgPlugins/x/CMakeFiles/osgdb_x.dir/build
.PHONY : osgdb_x/fast

#=============================================================================
# Target rules for targets named osgdb_dxf

# Build rule for target.
osgdb_dxf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_dxf
.PHONY : osgdb_dxf

# fast build rule for target.
osgdb_dxf/fast:
	$(MAKE) -f src/osgPlugins/dxf/CMakeFiles/osgdb_dxf.dir/build.make src/osgPlugins/dxf/CMakeFiles/osgdb_dxf.dir/build
.PHONY : osgdb_dxf/fast

#=============================================================================
# Target rules for targets named osgdb_openflight

# Build rule for target.
osgdb_openflight: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_openflight
.PHONY : osgdb_openflight

# fast build rule for target.
osgdb_openflight/fast:
	$(MAKE) -f src/osgPlugins/OpenFlight/CMakeFiles/osgdb_openflight.dir/build.make src/osgPlugins/OpenFlight/CMakeFiles/osgdb_openflight.dir/build
.PHONY : osgdb_openflight/fast

#=============================================================================
# Target rules for targets named osgdb_geo

# Build rule for target.
osgdb_geo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_geo
.PHONY : osgdb_geo

# fast build rule for target.
osgdb_geo/fast:
	$(MAKE) -f src/osgPlugins/geo/CMakeFiles/osgdb_geo.dir/build.make src/osgPlugins/geo/CMakeFiles/osgdb_geo.dir/build
.PHONY : osgdb_geo/fast

#=============================================================================
# Target rules for targets named osgdb_obj

# Build rule for target.
osgdb_obj: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_obj
.PHONY : osgdb_obj

# fast build rule for target.
osgdb_obj/fast:
	$(MAKE) -f src/osgPlugins/obj/CMakeFiles/osgdb_obj.dir/build.make src/osgPlugins/obj/CMakeFiles/osgdb_obj.dir/build
.PHONY : osgdb_obj/fast

#=============================================================================
# Target rules for targets named osgdb_pic

# Build rule for target.
osgdb_pic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_pic
.PHONY : osgdb_pic

# fast build rule for target.
osgdb_pic/fast:
	$(MAKE) -f src/osgPlugins/pic/CMakeFiles/osgdb_pic.dir/build.make src/osgPlugins/pic/CMakeFiles/osgdb_pic.dir/build
.PHONY : osgdb_pic/fast

#=============================================================================
# Target rules for targets named osgdb_stl

# Build rule for target.
osgdb_stl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_stl
.PHONY : osgdb_stl

# fast build rule for target.
osgdb_stl/fast:
	$(MAKE) -f src/osgPlugins/stl/CMakeFiles/osgdb_stl.dir/build.make src/osgPlugins/stl/CMakeFiles/osgdb_stl.dir/build
.PHONY : osgdb_stl/fast

#=============================================================================
# Target rules for targets named osgdb_3ds

# Build rule for target.
osgdb_3ds: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_3ds
.PHONY : osgdb_3ds

# fast build rule for target.
osgdb_3ds/fast:
	$(MAKE) -f src/osgPlugins/3ds/CMakeFiles/osgdb_3ds.dir/build.make src/osgPlugins/3ds/CMakeFiles/osgdb_3ds.dir/build
.PHONY : osgdb_3ds/fast

#=============================================================================
# Target rules for targets named osgdb_ac

# Build rule for target.
osgdb_ac: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_ac
.PHONY : osgdb_ac

# fast build rule for target.
osgdb_ac/fast:
	$(MAKE) -f src/osgPlugins/ac/CMakeFiles/osgdb_ac.dir/build.make src/osgPlugins/ac/CMakeFiles/osgdb_ac.dir/build
.PHONY : osgdb_ac/fast

#=============================================================================
# Target rules for targets named osgdb_pov

# Build rule for target.
osgdb_pov: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_pov
.PHONY : osgdb_pov

# fast build rule for target.
osgdb_pov/fast:
	$(MAKE) -f src/osgPlugins/pov/CMakeFiles/osgdb_pov.dir/build.make src/osgPlugins/pov/CMakeFiles/osgdb_pov.dir/build
.PHONY : osgdb_pov/fast

#=============================================================================
# Target rules for targets named osgdb_logo

# Build rule for target.
osgdb_logo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_logo
.PHONY : osgdb_logo

# fast build rule for target.
osgdb_logo/fast:
	$(MAKE) -f src/osgPlugins/logo/CMakeFiles/osgdb_logo.dir/build.make src/osgPlugins/logo/CMakeFiles/osgdb_logo.dir/build
.PHONY : osgdb_logo/fast

#=============================================================================
# Target rules for targets named osgdb_lws

# Build rule for target.
osgdb_lws: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_lws
.PHONY : osgdb_lws

# fast build rule for target.
osgdb_lws/fast:
	$(MAKE) -f src/osgPlugins/lws/CMakeFiles/osgdb_lws.dir/build.make src/osgPlugins/lws/CMakeFiles/osgdb_lws.dir/build
.PHONY : osgdb_lws/fast

#=============================================================================
# Target rules for targets named osgdb_md2

# Build rule for target.
osgdb_md2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_md2
.PHONY : osgdb_md2

# fast build rule for target.
osgdb_md2/fast:
	$(MAKE) -f src/osgPlugins/md2/CMakeFiles/osgdb_md2.dir/build.make src/osgPlugins/md2/CMakeFiles/osgdb_md2.dir/build
.PHONY : osgdb_md2/fast

#=============================================================================
# Target rules for targets named osgdb_osgtgz

# Build rule for target.
osgdb_osgtgz: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_osgtgz
.PHONY : osgdb_osgtgz

# fast build rule for target.
osgdb_osgtgz/fast:
	$(MAKE) -f src/osgPlugins/osgtgz/CMakeFiles/osgdb_osgtgz.dir/build.make src/osgPlugins/osgtgz/CMakeFiles/osgdb_osgtgz.dir/build
.PHONY : osgdb_osgtgz/fast

#=============================================================================
# Target rules for targets named osgdb_tgz

# Build rule for target.
osgdb_tgz: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_tgz
.PHONY : osgdb_tgz

# fast build rule for target.
osgdb_tgz/fast:
	$(MAKE) -f src/osgPlugins/tgz/CMakeFiles/osgdb_tgz.dir/build.make src/osgPlugins/tgz/CMakeFiles/osgdb_tgz.dir/build
.PHONY : osgdb_tgz/fast

#=============================================================================
# Target rules for targets named osgdb_shp

# Build rule for target.
osgdb_shp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_shp
.PHONY : osgdb_shp

# fast build rule for target.
osgdb_shp/fast:
	$(MAKE) -f src/osgPlugins/shp/CMakeFiles/osgdb_shp.dir/build.make src/osgPlugins/shp/CMakeFiles/osgdb_shp.dir/build
.PHONY : osgdb_shp/fast

#=============================================================================
# Target rules for targets named osgdb_txf

# Build rule for target.
osgdb_txf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_txf
.PHONY : osgdb_txf

# fast build rule for target.
osgdb_txf/fast:
	$(MAKE) -f src/osgPlugins/txf/CMakeFiles/osgdb_txf.dir/build.make src/osgPlugins/txf/CMakeFiles/osgdb_txf.dir/build
.PHONY : osgdb_txf/fast

#=============================================================================
# Target rules for targets named osgdb_bsp

# Build rule for target.
osgdb_bsp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_bsp
.PHONY : osgdb_bsp

# fast build rule for target.
osgdb_bsp/fast:
	$(MAKE) -f src/osgPlugins/bsp/CMakeFiles/osgdb_bsp.dir/build.make src/osgPlugins/bsp/CMakeFiles/osgdb_bsp.dir/build
.PHONY : osgdb_bsp/fast

#=============================================================================
# Target rules for targets named osgdb_mdl

# Build rule for target.
osgdb_mdl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_mdl
.PHONY : osgdb_mdl

# fast build rule for target.
osgdb_mdl/fast:
	$(MAKE) -f src/osgPlugins/mdl/CMakeFiles/osgdb_mdl.dir/build.make src/osgPlugins/mdl/CMakeFiles/osgdb_mdl.dir/build
.PHONY : osgdb_mdl/fast

#=============================================================================
# Target rules for targets named osgdb_ply

# Build rule for target.
osgdb_ply: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_ply
.PHONY : osgdb_ply

# fast build rule for target.
osgdb_ply/fast:
	$(MAKE) -f src/osgPlugins/ply/CMakeFiles/osgdb_ply.dir/build.make src/osgPlugins/ply/CMakeFiles/osgdb_ply.dir/build
.PHONY : osgdb_ply/fast

#=============================================================================
# Target rules for targets named osgdb_txp

# Build rule for target.
osgdb_txp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_txp
.PHONY : osgdb_txp

# fast build rule for target.
osgdb_txp/fast:
	$(MAKE) -f src/osgPlugins/txp/CMakeFiles/osgdb_txp.dir/build.make src/osgPlugins/txp/CMakeFiles/osgdb_txp.dir/build
.PHONY : osgdb_txp/fast

#=============================================================================
# Target rules for targets named osgdb_imageio

# Build rule for target.
osgdb_imageio: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_imageio
.PHONY : osgdb_imageio

# fast build rule for target.
osgdb_imageio/fast:
	$(MAKE) -f src/osgPlugins/imageio/CMakeFiles/osgdb_imageio.dir/build.make src/osgPlugins/imageio/CMakeFiles/osgdb_imageio.dir/build
.PHONY : osgdb_imageio/fast

#=============================================================================
# Target rules for targets named osgdb_freetype

# Build rule for target.
osgdb_freetype: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_freetype
.PHONY : osgdb_freetype

# fast build rule for target.
osgdb_freetype/fast:
	$(MAKE) -f src/osgPlugins/freetype/CMakeFiles/osgdb_freetype.dir/build.make src/osgPlugins/freetype/CMakeFiles/osgdb_freetype.dir/build
.PHONY : osgdb_freetype/fast

#=============================================================================
# Target rules for targets named osgdb_zip

# Build rule for target.
osgdb_zip: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_zip
.PHONY : osgdb_zip

# fast build rule for target.
osgdb_zip/fast:
	$(MAKE) -f src/osgPlugins/zip/CMakeFiles/osgdb_zip.dir/build.make src/osgPlugins/zip/CMakeFiles/osgdb_zip.dir/build
.PHONY : osgdb_zip/fast

#=============================================================================
# Target rules for targets named osgdb_pvr

# Build rule for target.
osgdb_pvr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 osgdb_pvr
.PHONY : osgdb_pvr

# fast build rule for target.
osgdb_pvr/fast:
	$(MAKE) -f src/osgPlugins/pvr/CMakeFiles/osgdb_pvr.dir/build.make src/osgPlugins/pvr/CMakeFiles/osgdb_pvr.dir/build
.PHONY : osgdb_pvr/fast

#=============================================================================
# Target rules for targets named application_osgviewer

# Build rule for target.
application_osgviewer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 application_osgviewer
.PHONY : application_osgviewer

# fast build rule for target.
application_osgviewer/fast:
	$(MAKE) -f applications/osgviewer/CMakeFiles/application_osgviewer.dir/build.make applications/osgviewer/CMakeFiles/application_osgviewer.dir/build
.PHONY : application_osgviewer/fast

#=============================================================================
# Target rules for targets named application_osgarchive

# Build rule for target.
application_osgarchive: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 application_osgarchive
.PHONY : application_osgarchive

# fast build rule for target.
application_osgarchive/fast:
	$(MAKE) -f applications/osgarchive/CMakeFiles/application_osgarchive.dir/build.make applications/osgarchive/CMakeFiles/application_osgarchive.dir/build
.PHONY : application_osgarchive/fast

#=============================================================================
# Target rules for targets named application_osgconv

# Build rule for target.
application_osgconv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 application_osgconv
.PHONY : application_osgconv

# fast build rule for target.
application_osgconv/fast:
	$(MAKE) -f applications/osgconv/CMakeFiles/application_osgconv.dir/build.make applications/osgconv/CMakeFiles/application_osgconv.dir/build
.PHONY : application_osgconv/fast

#=============================================================================
# Target rules for targets named application_osgfilecache

# Build rule for target.
application_osgfilecache: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 application_osgfilecache
.PHONY : application_osgfilecache

# fast build rule for target.
application_osgfilecache/fast:
	$(MAKE) -f applications/osgfilecache/CMakeFiles/application_osgfilecache.dir/build.make applications/osgfilecache/CMakeFiles/application_osgfilecache.dir/build
.PHONY : application_osgfilecache/fast

#=============================================================================
# Target rules for targets named application_osgversion

# Build rule for target.
application_osgversion: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 application_osgversion
.PHONY : application_osgversion

# fast build rule for target.
application_osgversion/fast:
	$(MAKE) -f applications/osgversion/CMakeFiles/application_osgversion.dir/build.make applications/osgversion/CMakeFiles/application_osgversion.dir/build
.PHONY : application_osgversion/fast

#=============================================================================
# Target rules for targets named application_present3D

# Build rule for target.
application_present3D: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 application_present3D
.PHONY : application_present3D

# fast build rule for target.
application_present3D/fast:
	$(MAKE) -f applications/present3D/CMakeFiles/application_present3D.dir/build.make applications/present3D/CMakeFiles/application_present3D.dir/build
.PHONY : application_present3D/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... uninstall"
	@echo "... OpenThreads"
	@echo "... osg"
	@echo "... osgDB"
	@echo "... osgUtil"
	@echo "... osgGA"
	@echo "... osgText"
	@echo "... osgViewer"
	@echo "... osgAnimation"
	@echo "... osgFX"
	@echo "... osgManipulator"
	@echo "... osgParticle"
	@echo "... osgPresentation"
	@echo "... osgShadow"
	@echo "... osgSim"
	@echo "... osgTerrain"
	@echo "... osgWidget"
	@echo "... osgVolume"
	@echo "... osgdb_serializers_osg"
	@echo "... osgdb_serializers_osganimation"
	@echo "... osgdb_serializers_osgfx"
	@echo "... osgdb_serializers_osgmanipulator"
	@echo "... osgdb_serializers_osgparticle"
	@echo "... osgdb_serializers_osgsim"
	@echo "... osgdb_serializers_osgshadow"
	@echo "... osgdb_serializers_osgterrain"
	@echo "... osgdb_serializers_osgtext"
	@echo "... osgdb_serializers_osgvolume"
	@echo "... osgdb_deprecated_osg"
	@echo "... osgdb_deprecated_osgparticle"
	@echo "... osgdb_deprecated_osganimation"
	@echo "... osgdb_deprecated_osgfx"
	@echo "... osgdb_deprecated_osgsim"
	@echo "... osgdb_deprecated_osgtext"
	@echo "... osgdb_deprecated_osgviewer"
	@echo "... osgdb_deprecated_osgshadow"
	@echo "... osgdb_deprecated_osgterrain"
	@echo "... osgdb_deprecated_osgvolume"
	@echo "... osgdb_deprecated_osgwidget"
	@echo "... osgdb_osga"
	@echo "... osgdb_rot"
	@echo "... osgdb_scale"
	@echo "... osgdb_trans"
	@echo "... osgdb_normals"
	@echo "... osgdb_revisions"
	@echo "... osgdb_osgviewer"
	@echo "... osgdb_osgshadow"
	@echo "... osgdb_osgterrain"
	@echo "... osgdb_osg"
	@echo "... osgdb_ive"
	@echo "... osgdb_cfg"
	@echo "... osgdb_glsl"
	@echo "... osgdb_rgb"
	@echo "... osgdb_bmp"
	@echo "... osgdb_pnm"
	@echo "... osgdb_dds"
	@echo "... osgdb_tga"
	@echo "... osgdb_hdr"
	@echo "... osgdb_dot"
	@echo "... osgdb_vtf"
	@echo "... osgdb_3dc"
	@echo "... osgdb_p3d"
	@echo "... osgdb_curl"
	@echo "... osgdb_gz"
	@echo "... osgdb_lwo"
	@echo "... osgdb_dw"
	@echo "... osgdb_bvh"
	@echo "... osgdb_x"
	@echo "... osgdb_dxf"
	@echo "... osgdb_openflight"
	@echo "... osgdb_geo"
	@echo "... osgdb_obj"
	@echo "... osgdb_pic"
	@echo "... osgdb_stl"
	@echo "... osgdb_3ds"
	@echo "... osgdb_ac"
	@echo "... osgdb_pov"
	@echo "... osgdb_logo"
	@echo "... osgdb_lws"
	@echo "... osgdb_md2"
	@echo "... osgdb_osgtgz"
	@echo "... osgdb_tgz"
	@echo "... osgdb_shp"
	@echo "... osgdb_txf"
	@echo "... osgdb_bsp"
	@echo "... osgdb_mdl"
	@echo "... osgdb_ply"
	@echo "... osgdb_txp"
	@echo "... osgdb_imageio"
	@echo "... osgdb_freetype"
	@echo "... osgdb_zip"
	@echo "... osgdb_pvr"
	@echo "... application_osgviewer"
	@echo "... application_osgarchive"
	@echo "... application_osgconv"
	@echo "... application_osgfilecache"
	@echo "... application_osgversion"
	@echo "... application_present3D"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

